# Generated by Django 5.1.4 on 2024-12-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="portfolio_history",
            field=models.JSONField(default=list),
        ),
    ]
