# Generated by Django 5.1.4 on 2024-12-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_team_portfolio_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="portfolio_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
