# Generated by Django 5.1.4 on 2025-01-05 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_alter_team_portfolio_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationrequest",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_request",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Offen"),
                    ("closed", "Abgeschlossen"),
                    ("canceled", "Storniert"),
                    ("error", "Fehler"),
                ],
                default="open",
                max_length=10,
            ),
        ),
    ]
