# Generated by Django 5.1.4 on 2025-01-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_alter_registrationrequest_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
    ]
