# Generated by Django 5.1.2 on 2024-10-16 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholding',
            name='stock',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='holdings',
                to='stocks.stock'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
