# Generated by Django 5.1.5 on 2025-01-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_remove_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="errors",
            field=models.TextField(blank=True),
        ),
    ]
