# Generated by Django 5.1.5 on 2025-01-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0006_transaction_errors"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_edited",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
