# Generated by Django 5.1.5 on 2025-02-03 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0007_userprofile_last_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_edited",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
