# Generated by Django 5.1.2 on 2024-10-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0009_alter_userprofile_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(default="open", max_length=10),
        ),
    ]
