# Generated by Django 5.1.5 on 2025-02-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0009_alter_userprofile_last_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_admin",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_of_team",
                to="stocks.userprofile",
            ),
        ),
    ]
