# Generated by Django 5.1.5 on 2025-02-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0010_team_team_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="last_edited",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
