# Generated by Django 5.1.2 on 2024-10-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0012_alter_stockholding_stock_alter_stockholding_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="name",
            field=models.CharField(
                choices=[
                    ("Day", "Tag"),
                    ("5 Days", "5 Tage"),
                    ("Month", "Monat"),
                    ("3 Months", "3 Monate"),
                    ("Year", "Jahr"),
                    ("5 Years", "5 Jahre"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="current_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="team",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("canceled", "Canceled"),
                    ("error", "Error"),
                ],
                default="open",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("buy", "Kaufen"), ("sell", "Verkaufen")], max_length=5
            ),
        ),
    ]
