# Generated by Django 5.1.2 on 2024-10-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0013_alter_history_name_alter_stock_current_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("buy", "Kaufen"), ("sell", "Verkaufen")], max_length=10
            ),
        ),
    ]
