# Generated by Django 5.1.2 on 2024-10-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0014_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreadControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.BooleanField(default=False, unique=True)),
            ],
        ),
    ]
