# Generated by Django 5.1.2 on 2024-11-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0015_threadcontrol"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ThreadControl",
        ),
    ]
