# Generated by Django 5.1.2 on 2024-11-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0016_delete_threadcontrol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
