# Generated by Django 5.1.3 on 2024-11-07 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0019_alter_watchlist_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
