# Generated by Django 5.1.3 on 2024-11-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0021_registrationrequest_userprofile_nickname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="code",
            field=models.CharField(
                blank=True, default="asdfgh", max_length=6, null=True
            ),
        ),
    ]
