# Generated by Django 5.1.3 on 2024-11-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0022_team_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="code",
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
